### ISSUE TITLE
ECS Frame Title Bar - border one pixel off (?)

### ISSUE THREAD

**Issue by boktai1000** [BreakBB/ExtendedCharacterStats#130] opened 2021-06-16 21:06 UTC
## Bug description
The frame for ECS has a part where it connects, but it's one pixel off (see screenshot below, putting this into words is harder than I realized). I'm not entirely sure if this texture/etc is just pulled directly from WoW, or it's artistic flavor, and if so, sorry! I just noticed it, and couldn't un-notice, and if it's completely intentional then just close what may be the silliest bug report you've seen :)

Your screenshot here as well shows this as well: https://user-images.githubusercontent.com/33514570/120346975-2ac47f80-c2fc-11eb-90d4-c012a1e56296.png

## Screenshots
![image](https://user-images.githubusercontent.com/9054563/122293218-69d9ff80-cebc-11eb-8e8f-11098ed5b0d1.png)

## Version
ECS v2.8.6 (BC Classic in my test)

Thanks for the great addon!

**Comment by BreakBB** [comment] 2021-06-24 16:51
Duplicate of #57

I didn't find a proper solution for this yet, sorry.

**Closed by BreakBB** 2021-06-24 16:51 UTC
Labels: bug
