### ISSUE TITLE
Latest Classic Bug

### ISSUE THREAD

**Issue by DanLloyd87** [BreakBB/ExtendedCharacterStats#162] opened 2021-11-12 03:34 UTC
## Bug description
Created a level 1 Undead Warlock.

Lua Error Dump below:
Message: ...ns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:20: Usage: GetSpellCritChance(school)
Time: Fri Nov 12 13:23:24 2021
Count: 1
Stack: ...ns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:20: Usage: GetSpellCritChance(school)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCritChance'
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua"]:20: in function <...ns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:12>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:167: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:165>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:159: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:148>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:217: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:184>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:104: in function `CreateWindow'
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Init.lua"]:30: in function `OnPlayerLogin'
[string "@Interface\AddOns\ExtendedCharacterStats\ECS.lua"]:22: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:15>

Locals: 

## Version
ECS v2.8.11
WoW Classic Era

**Comment by DanLloyd87** [comment] 2021-11-12 03:35
Additionally when pressing Settings button I get

Lua Error Dump below:
Message: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:56: attempt to index global 'ECSConfigFrame' (a nil value)
Time: Fri Nov 12 13:35:13 2021
Count: 1
Stack: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:56: attempt to index global 'ECSConfigFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:56: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:55>

Locals:

**Comment by BreakBB** [comment] 2021-11-12 11:29
Duplicate of #157 

If you are willing to test an unofficial version check that issue @DanLloyd87 

The error you posted are fixed in that version (which I should release) 🙈

**Closed by BreakBB** 2021-11-12 11:29 UTC
Labels: bug
