### ISSUE TITLE
ECS v2.8.8 (latest update) breaks other addons/functionality.

### ISSUE THREAD

**Issue by Ereperez** [BreakBB/ExtendedCharacterStats#143] opened 2021-07-03 14:57 UTC
## Bug description

Can't for example open my bags at all, even when disabling Bagnon. Seems to break other functionality too like buy windows from vendors. Broken update.

## Version
 
Version 2.8.8

**Comment by Onetail123** [comment] 2021-07-03 15:08
I've also seen that the latest update prevents your map from loading even if you've discovered areas and specifically on Paladins, it prevents questie from working

**Comment by Orami9b** [comment] 2021-07-03 16:49
With the latest version, I get errors only when logging on Paladin. "Attempting to call method GetHealingPower" and "attempt to call global 'mod'" (this one blows up with several counts) are the lua errors given. Bags can't be opened, macro page is unusable, and also breaks a few other addons. No issues at all when on warrior or warlock.

**Comment by DarthKnight01** [comment] 2021-07-03 16:50
Can Confirm That its preventing other addons from working like gathermate/Questie

**Comment by Psiblades** [comment] 2021-07-03 21:56
Can also confirm. Breaks Bagnon and prevents Questie from intializing

**Comment by Catreina** [comment] 2021-07-03 21:58
Duplicate of https://github.com/BreakBB/ExtendedCharacterStats/issues/144

**Closed** 2021-07-04 16:21 UTC
Labels: bug

**Comment by BreakBB** [comment] 2021-07-05 05:14
@Ereperez @Onetail123 @Orami9b @DarthKnight01 @Psiblades @Catreina 

Sorry for the broken update v2.8.8 - I've released v2.8.9 yesterday which fixes this major issue, make sure to update.
