### ISSUE TITLE
BUG with Block value

### ISSUE THREAD

**Issue by uliponh** [BreakBB/ExtendedCharacterStats#60] opened 2020-09-03 23:00 UTC

**Comment by BreakBB** [comment] 2020-09-06 15:54
@uliponh Please provide some information on this.

**Comment by uliponh** [comment] 2020-09-06 18:36
![ECSBUG1](https://user-images.githubusercontent.com/70728055/92332733-50b34100-f056-11ea-8e87-2636ee26854b.JPG)
![ECSBUG2](https://user-images.githubusercontent.com/70728055/92332734-51e46e00-f056-11ea-8005-9723b3fe6dba.JPG)
![ECSBUG3](https://user-images.githubusercontent.com/70728055/92332736-51e46e00-f056-11ea-8e71-38fd0f110067.JPG)
![ECSBUG4](https://user-images.githubusercontent.com/70728055/92332737-527d0480-f056-11ea-842e-5e35d2938654.JPG)
 The sum of the block value with the sabatons of wrath is lower than the sum with the boots of the fallen hero, but the second one dont have block value, something is buggy with this.

**Comment by BreakBB** [comment] 2020-09-11 10:49
Hey @uliponh could you run the following command ingame and report the output? With the Sabatons of Wrath and the Boots of the Fallen Hero.

`/dump GetShieldBlock()`

**Comment by BreakBB** [comment] 2021-04-11 19:39
Closing this as I can't reproduce it.

**Closed by BreakBB** 2021-04-11 19:39 UTC
Labels: bug
