### ISSUE TITLE
Fix pls defense bonus.

### ISSUE THREAD

**Issue by Tikinokys** [BreakBB/ExtendedCharacterStats#81] opened 2020-10-19 18:15 UTC
## Bug description

Hi. I'm a Tank and this addon don't show defense bonus. 300+0 always. Fix pls that.

## Screenshots

![2020-10-19_21-12-04](https://user-images.githubusercontent.com/14983202/96495072-f958e100-124f-11eb-9cc1-c08febd0ced4.png)

## Version

2.6.2

**Comment by BreakBB** [comment] 2020-10-20 17:31
Hey @Tikinokys thanks for the report. I think you have item which grant + Defense, which doesn't show up. Am I correct?

**Comment by Tikinokys** [comment] 2020-10-21 15:09
> Hey @Tikinokys thanks for the report. I think you have item which grant + Defense, which doesn't show up. Am I correct?

Yeah. I have around 400 defense with my items. But This Addon don't show that.

**Comment by BreakBB** [comment] 2020-10-31 21:25
Hey @Tikinokys I just checked this on a char where I have "Heavy Dark Iron Ring" which gives +5 Defense. I see it in ECS.
![grafik](https://user-images.githubusercontent.com/33514570/97790325-fa7efc00-1bc7-11eb-9863-f9199d5ea29a.png)


Which items do you have equiped that you don't see it?

**Comment by Tikinokys** [comment] 2020-11-02 02:37
> Hey @Tikinokys I just checked this on a char where I have "Heavy Dark Iron Ring" which gives +5 Defense. I see it in ECS.
> ![grafik](https://user-images.githubusercontent.com/33514570/97790325-fa7efc00-1bc7-11eb-9863-f9199d5ea29a.png)
> 
> Which items do you have equiped that you don't see it?

Full T2 warrior set, T2.5 items and another def items. All my friends who use this addon have this bug.

**Comment by BreakBB** [comment] 2020-11-06 07:18
Thanks for coming back to this @Tikinokys then it might be that some items are not handled correctly. I will look for a way to fix this properly!

**Comment by BreakBB** [comment] 2020-11-07 10:25
@Tikinokys I asked a guild member of mine to equip all his defense items he has and ECS correctly shows `300 + 38`. I also bought some stuff from the AH which results in `300 + 9`:

![grafik](https://user-images.githubusercontent.com/33514570/98438559-50353600-20eb-11eb-9721-940c6b3aa596.png)

Could you test to equip one item at a time to see if any of the items bugs ECS out? Maybe also send a list of the items you equip?

**Comment by Tikinokys** [comment] 2020-11-08 11:18
Mb problems with localization? I can't check this addon on English.

**Comment by BreakBB** [comment] 2020-11-16 11:18
Sorry again for the late response @Tikinokys . What language are you using? Maybe that is indeed the issue.

**Comment by Pengomat** [comment] 2020-11-26 10:39
Hey block value is calculated wrong. If I put off styleens scarab - My block Value doestn change
![image](https://user-images.githubusercontent.com/6883832/100340766-f635db00-2fdb-11eb-9896-a8da7d6de94e.png)

![image](https://user-images.githubusercontent.com/6883832/100340793-ffbf4300-2fdb-11eb-89b7-b680c8551e48.png)

**Comment by BreakBB** [comment] 2020-12-01 19:14
Hmmm @Pengomat you are using the latest version of ECS, right? Could you run the following command with and without the trinket?

`/dump GetShieldBlock()`

**Comment by BreakBB** [comment] 2021-04-11 19:40
Closing this as I can't reproduce it.

**Closed by BreakBB** 2021-04-11 19:40 UTC
Labels: bug
